services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: crm-backend
    volumes:
      - ./backend:/usr/src/app
      - backend_node_modules:/usr/src/app/node_modules
    env_file:
      - ./.env
    environment:
      - RUNNING_IN_DOCKER=true
    ports:
      - '9032:3000'
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: crm-frontend
    volumes:
      - ./frontend:/usr/src/app
      - frontend_node_modules:/usr/src/app/node_modules
    environment:
      - NODE_ENV=development
    ports:
      - '9034:3000'
    depends_on:
      - backend
    restart: unless-stopped
  
  whatsapp-api:
    build:
      context: ./backend/whatsapp-api
      dockerfile: Dockerfile
    container_name: crm-whatsapp-api
    ports:
      - '9033:3000'
    volumes:
      - whatsapp_data:/app/wa_data
    environment:
      - PORT=3000
      - WEBHOOK_URL=http://backend:3000/api/whatsapp/webhooks/whatsapp
      - WA_DATA_PATH=/app/wa_data
      - PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium-browser
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  backend_node_modules:
  frontend_node_modules:
  whatsapp_data: